### ISSUE TITLE
[BUG] Video mode pixel scaling width and height no longer save to settings file

### ISSUE THREAD

**Issue by Snoturky** [ZDoom/gzdoom#1896]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro 22H2 19045.2364

### Relevant hardware info

Intel i5 13600KF, RTX 3070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Custom Width (vid_scale_customwidth) and Custom Height (vid_scale_customheight) under the Custom Pixel Scaling section do not save to the settings file (/Documents/My Games/GZDoom/gzdoom.ini) anymore.

This is not a problem with a missing file or write permission. Most things _are_ being saved, so saving in general does work - the config file is found and can be written by GZDoom. The problem is that changes to these two specific variables are no longer updated in the settings file.

![image](https://user-images.githubusercontent.com/7218853/209276440-a40427cf-f001-4f58-bf4a-b99b9953a9ef.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install GZDoom to any directory (doesn't matter where because the ini file is now in /Documents/My Games/GZDoom as of v4.9.0)
2. Delete existing config file located at /Documents/My Games/GZDoom/gzdoom.ini
3. Start GZDoom with Doom 2 iwad.
4. Options > Full options menu > Set video mode > Choose Resolution Preset > (whatever you want, I use 2560x1440)
5. Apply Changes (Fullscreen)
6. Go back one level in Options menu > Save current settings
7. Exit game and restart - the resolution is back to default 320x200 and vid_scale_customheight and vid_scale_customwidth in the settings file still read 200 and 320. If you make other changes (such as Use Linear Scaling) it _will_ toggle between true and false in the settings file (/Documents/My Games/GZDoom/gzdoom.ini)

**Comment by mjr4077au** [comment]
Also reported in Raze, so a fix either side closes the other side's bug: https://github.com/ZDoom/Raze/issues/780.

**Comment by JMartinez9820** [comment]
I've been getting the same issue too! It's really making me angry. I'm going to be downgrading to 4.8.2 until this is fixed. The resolution settings not being saved is a MAJOR issue and it's just unacceptable.

**Comment by mjr4077au** [comment]
> I've been getting the same issue too! It's really making me angry. I'm going to be downgrading to 4.8.2 until this is fixed. The resolution settings not being saved is a MAJOR issue and it's just unacceptable.

@JMartinez9820 relax, mate. Mistakes occur from time to time and that's all this is. That kind of vitriol is what's unacceptable.

**Comment by JMartinez9820** [comment]
Do you think I care? No. As a person who mostly plays at 16:9, I want it to stay at that resolution, not change all of the time. I think you can force it with autoexec but idk how it's done resolution. I just hope the final build of GZDoom 4.11.0 fixes it because the dev builds don't.

**Comment by madame-rachelle** [comment]
As a reminder this is a project that is done for free, and it was never made to "prove" anything to you, it's just a hobby that a few of us work on in our spare time. You aren't owed anything, so calling something "unacceptable" reflects more on you than it does us. You can "don't care" all you want but, it's not going to get your problems solved any faster. You can stick with the 4.8.x series until we get this one fixed. Sorry that we don't work fast enough for you, Your Highness. Either way though, rest assured that it is in our hit list and we plan to tackle it as soon as possible.

**Comment by JMartinez9820** [comment]
I only said that it was unacceptable because it can be a real pain in the neck to change the resolution to what I want it to be every time. Now I might just go hurt myself, because everything I say is redundant, invalid and I probably did something wrong. It was my fault for not being aware of the words I said, and I sincerely apologize for it. I was just trying to voice my opinion on this issue, but now I know to try to use more constructive criticism instead of sounding harsh. I promise that will never happen again.

**Comment by madame-rachelle** [comment]
One thing you can do is run post 4.9, use it to find your config, exit, then delete the config; configure in 4.8.2 the way you want your settings to actually be, then rerun 4.10, and it will use the new "old" settings instead of what it had before.

**Comment by CandiceJoy** [comment]
Fixed in https://github.com/ZDoom/gzdoom/pull/1909 :)

**Comment by WiLLuMPJuH** [comment]
Thank you for your consideration ( and your hard work on the application of course ) . I can understand JMartinez9820 frustration however. I enjoy his videos a lot. It's very unnerving to have to change it every single instance. Myself I am enjoying the new release very much, yet this resolution issue was very annoying when switching and restarting the application a lot ( to try out all sorts of mods ). Happy to read it's been dealt with and committed. Honestly. Thank you.

**Comment by WiLLuMPJuH** [comment]
Thank you for your consideration ( and your hard work on the application of course ) . I can understand JMartinez9820 frustration however. I enjoy his videos a lot. It's very unnerving to have to change it every single instance. Myself I am enjoying the new release very much, yet this resolution issue was very annoying when switching and restarting the application a lot ( to try out all sorts of mods ). Happy to read it's been dealt with and committed. Honestly. Thank you.

**Comment by maxlefou** [comment]
I confirm this bug on linux.
It actually started doing it to me when i had to switch from fullscreen to windowed. Manually setting the resolution in the ini fixed it.

**Comment by maxlefou** [comment]
Sorry to bother, but this bug is still present on Linux with the version g4.10.0-m.
It didn't trigger before I switched from fullscreen to windowed.
Doesn't occur anymore if I set the resolution manually in the ini file.

**Comment by JMartinez9820** [comment]
Unless you're using Linux, I would downgrade to GZDoom 4.8.2 for now. The new versions are garbage, and the fact that this issue still hasn't been fixed gives the users more headaches than it should be

**Comment by CandiceJoy** [comment]
> Unless you're using Linux, I would downgrade to GZDoom 4.8.2 for now. The new versions are garbage, and the fact that this issue still hasn't been fixed gives the users more headaches than it should be

This **has** been fixed, there just hasn't been a version released since the fix.

**Comment by maxlefou** [comment]
> Unless you're using Linux, 
I **am** using linux :D

**Comment by CandiceJoy** [comment]
> > Unless you're using Linux,
> 
> I **am** using linux :D

The bug isn’t OS-dependent. The issue was missing dereference operators :p

**Comment by JMartinez9820** [comment]
I have deleted all of my messages because all of my opinions are redundant. I feel like I've done something wrong and hurt someone's feelings, I'm sorry if I did something wrong. Someday I might just take my own life because I don't deserve it anymore
